### ISSUE TITLE
Cluster pods won't come up as /data/humio-data is mounted as readOnly

### ISSUE THREAD

**Issue by brightzheng100** [humio/humio-operator#350]
It suddenly couldn't work anymore from a couple of days back, I tried even the latest version.

The issue is that the PVC is mounted to `/data/humio-data` as readOnly while there is a file expected there: `/data/humio-data/local-admin-token.txt`.

So the pod comes to CrashLoopBackOff:

```sh
$ kgp
NAME                             READY   STATUS             RESTARTS   AGE
humio-cluster-core-jedpjy        1/2     CrashLoopBackOff   5          5m46s
humio-operator-7646858d4-7qn8b   1/1     Running            0          6m1s
```

With logs:
```log
2021-03-18T00:57:34.066+0000 [main] ERROR c.h.m.ServerRunner$ -1 - Got exception starting pid=1 org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:499) ~[humio-assembly.jar:0.1]
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:63) ~[humio-assembly.jar:0.1]
	at com.humio.kafka.KafkaAdminUtils.<init>(KafkaAdminUtils.scala:58) ~[humio-assembly.jar:0.1]
	at com.humio.kafka.KafkaAdminUtils$.apply(KafkaAdminUtils.scala:27) ~[humio-assembly.jar:0.1]
	at com.humio.kafka.GlobalKafka.setupKafkaQueues(Global.scala:124) ~[humio-assembly.jar:0.1]
	at com.humio.kafka.GlobalKafka.<init>(Global.scala:110) ~[humio-assembly.jar:0.1]
	at com.humio.kafka.GlobalKafka.<init>(Global.scala:95) ~[humio-assembly.jar:0.1]
	at com.humio.core.Config$.fromEnv(Config.scala:1539) ~[humio-assembly.jar:0.1]
	at com.humio.main.ServerRunner$.main(ServerRunner.scala:102) ~[humio-assembly.jar:0.1]
	at com.humio.main.ServerRunner.main(ServerRunner.scala) ~[humio-assembly.jar:0.1]
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89) ~[humio-assembly.jar:0.1]
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48) ~[humio-assembly.jar:0.1]
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:455) ~[humio-assembly.jar:0.1]
	... 9 more
Starting humio-operator-helper version 0.2.0
waiting on files /data/humio-data/local-admin-token.txt, /data/humio-data/global-data-snapshot.json
waiting on files /data/humio-data/local-admin-token.txt, /data/humio-data/global-data-snapshot.json
...
```

And this is the troubleshooting:

```sh
$ kexec -it humio-cluster-core-jedpjy -c auth -- bash
bash-4.4$ ls /data/humio-data
lost+found  tmp
bash-4.4$ cd /data/humio-data
bash-4.4$ touch test.txt
touch: cannot touch 'test.txt': Read-only file system
```

And this is the yaml:
```yaml
  containers:
  - image: humio/humio-operator-helper:0.2.0
    name: auth
    ...
    volumeMounts:
    - mountPath: /data/humio-data
      name: humio-data
      readOnly: true
```

**Comment by brightzheng100** [comment]
Double checked: this issue breaks all the versions I've tested: v0.5.0, v0.5.1, v0.6.1

**Comment by brightzheng100** [comment]
This could be a false alarm: with some tweaks around Storage Class, Humio Operator actually works fine.

**Comment by doormat18** [comment]
@brightzheng100 could you comment on which storage class changes you made?
